version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    container_name: web
    networks:
      - "n1"
      - "n2"

  mysql:
    image: "mysql"
    volumes:
     - "myvolume:/home/node/app"
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "goku"
      MYSQL_DATABASE: "mydatabase"
    networks:
      - "n1"
  alpine:
    image: alpine
    container_name: alpine
    stdin_open: true
    networks:
      - "n2"
volumes:
 myvolume:
  external: true
networks:
    n1:
     external:
        name: network1
    n2:
     external:
        name: network2
